
services:
  backend:
    container_name: python
    build: 
      context: '.'
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8000:8000
    tty: true
  
  frontend:
    container_name: react
    build: 
      context: '.'
      dockerfile: ./frontend/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules # node_modules
    tty: true
    depends_on:
      - backend

volumes:
  node_modules:
